### PR TITLE
Das 10

### PR DESCRIPTION
**Pull request by shortaflip**
# <Summary of PR>
Refactored some helper functions for competition tests.  Added tests for partnership
## Changes
Tested Functions:
1.  HasAthlete
2.  GetPartnershipByID
3.  MustGetPartnershipByID
## Fixed Issues
N/A
## Known Issues
TestCreateCompetition failed - will check.
## Local Test Coverage
Businesslogic: 39.9%

### CODE REVIEW

**Comment by shortaflip** [comment]
@yubing24 Can I have a rebuild of this Pull Request?  

This test passes on local run using `go test` and `go test competition_test.go` and the test passes after pushing the branch to remote.  However, the test failed on the pull request.
`--- FAIL: TestCreateCompetition (0.00s)`

**Problem**
`1 http://www.example.com`:  the 1 is the StatusID of what the test gets.
`0 http://www.example.com`:  the 0 is the StatusID of what the test wants.

Since they are not equal the build failed.  I do not know why the StatusID is **1** since it was never initialized in the test and should remain 0.

**Comment by yubing24** [comment]
@shortaflip: StatusID 0 is not a valid state. The CreateCompetition function forces all new competition to be in status 1, which is pre-registration.
See businesslogic/competitionstatus.go for a list of valid status ID

**Comment by shortaflip** [comment]
Ok got it, I'll look through some possibilities then.

**Comment by shortaflip** [comment]
@yubing24 I looked into it again and the test that you wrote passes locally at the very least.  

image

The top one is the competition struct given to the test and the bottom is what it wants.  The bottom number, as you say, shouldn't be a zero.  I haven't touched your test code at all so it might just have been a bug?

Anyway, how do we want to proceed from here?  Should I close this pull request and just make another one or do you have the ability to re-run the failed tests above?

**Pull request closed without merging**
